### ISSUE TITLE
Saving functionality System.UnauthorizedAccessException with the files. 

### ISSUE THREAD

**Issue by Gabeele** [bbowler1740/CSCN72030-Anemoi#3]
https://github.com/bbowler1740/CSCN72030-Anemoi/blob/b100b84ff9490bcd655dc8222f74202823d92f5d/CSCN72030-Anemoi/DeviceListLocation/DeviceList.cs#L92

Saving functionality does not create the file. The exception thrown indicates a permission issue. It can be replicated through running the program and passing through a string.

**Comment by Gabeele** [comment]
Found a possible solution using 

```
Windows.Storage.StorageFolder storageFolder = Windows.Storage.ApplicationData.Current.LocalFolder;
 Windows.Storage.StorageFile file = await storageFolder.CreateFileAsync("test.txt", Windows.Storage.CreationCollisionOption.OpenIfExists);
```
After some preliminary testing, we could use the local folder for our system.

**Comment by KevinMcDanielConestoga** [comment]
The problem seems to be that UWP applications cannot save to any directory without permissions from the user (using a file picker). Since, MS has restricted where we can save/write files we must use the "LocalFolder" for the application. We can continue using our writing syntax, we just need to use the directory path of "LocalFolder" (rather than the executables environment directory)
